### ISSUE TITLE
Build failure with JUCE 8.0.13

### ISSUE THREAD

**Issue by merkys** [marcus-w-hobbs/Wilsonic-MTS-ESP#9]
Build with JUCE 8.0.13 fails with the following:
```
../../Source/FavoritesModelV2.cpp: In member function 'int FavoritesModelV2::getColumnAutoSizeWidth(int)':
../../Source/FavoritesModelV2.cpp:795:41: error: 'class juce::Font' has no member named 'getStringWidth'
  795 |             widest = jmax(widest, _font.getStringWidth(text));
      |                                         ^~~~~~~~~~~~~~
```

It seems that JUCE no longer exposes `juce::Font::getStringWidth()`.

Build attempted on Debian unstable arch:x86_64 with system-provided JUCE packages.
